safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Trisha Zdziarska"
description: "My online studio"
baseurl: ""
url: "http://trisha.studio/blog" # replace by your site's url
twitter_username: your-name
github_username:  lukas-h # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Trisha Zdziarska"
address: "Your Street, <br>Your City, Country"
email: "trishazdz@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
