safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Patrycja Zdziarska"
description: "My online studio"
baseurl: ""
url: "http://trisha.studio" # replace by your site's url
twitter_username: your-name
github_username:  lukas-h # (your name)
accent: "#fff" # accent color for blog column

author: "Patrycja Zdziarska"
address: "Your Street, <br>Your City, Country"
email: "pzdziars@iu.edu"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
